---
# handlers file for sample-apache
- name: Restart "{{ service }}"
  service: 
    name: "{{ service }}"
    state: restarted

- name: Reload firewalld
  service:
    name: firewalld
    state: restarted
