---
- name: Deploy instance to openstack
  hosts: localhost
  tasks:
  - name: Download ubuntu image
    get_url:
      url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
      dest: /tmp/bionic.img
  - name: Upload image to openstack
    os_image:
      auth:
         auth_url: http://10.1.29.40/identity
         username: admin
         password: secret
         project_name: admin
         os_user_domain_name: Default
         os_project_domain_name: Default
      name: bionic
      container_format: bare
      disk_format: qcow2
      state: present
      filename: /tmp/bionic.img

  - name: Create SSH key
    os_keypair:
      auth:
         auth_url: http://10.1.29.40/identity
         username: admin
         password: secret
         project_name: admin
         os_user_domain_name: Default
         os_project_domain_name: Default
      state: present
      name: root
      public_key_file: "{{ '~' | expanduser }}/.ssh/id_rsa.pub"

  - name: Create the instance
    os_server:
      auth:
         auth_url: http://10.1.29.40/identity
         username: admin
         password: secret
         project_name: admin
         os_user_domain_name: Default
         os_project_domain_name: Default
      state: present
      name: bionic
      image: bionic
      flavor: m1.small
      security_groups: default
      key_name: root
      nics:
        - net-id: fc7db8ed-1c2e-4a40-8e13-0ab6ccfdff35
    register: bionic

  - name: Show instance IP
    debug: var=bionic.openstack.public_v4

  - name: add host to inventory
    add_host: hostname=bionic groups=linux
  - name: see group
    debug: var=group_names
