# изначально решил задачу с выполнением bash-скрипта ip.sh, что громоздко и неправильно
# но это работало
# в итоге, правильно - подкладывать в шаблон j2 переменную {{ ansible_default_ipv4.address }}
# и не париться
# оставляю в репозитории первый вариант, т.к. он интереснее по реализации
---
- name: role sample-apache
  hosts: webservers
  become: yes

  roles:
    - { role: sample-apache, when: ansible_system == 'Linux' }
