#Create a playbook /home/automation/plays/sshd.yml that runs on all inventory hosts and configures SSHD daemon as follows:
#banner is set to /etc/motd
#X11Forwarding is disabled
#MaxAuthTries is set to 3

---
- hosts: all
  tasks:
  - name: replace the strings
    replace:
      path: /etc/ssh/sshd_config
      backup: yes
      regexp: "{{item.reg}}"
      replace: "{{item.replace}}"
    with_items:
    - { reg: '^(.*)Banner(.*)$', replace: 'Banner=/etc/motd' }
    - { reg: '^X11Forwarding(.*)$', replace: 'X11Forwarding no' }
    - { reg: '^(.*)MaxAuthTries(.*)$', replace: 'MaxAuthTries 3' }
