---
- hosts: proxy
  tasks:
  - name: Replace the content of file
    shell:
      chdir: /etc
      cmd: echo "Welcome to HAProxy server" > motd
- hosts: webservers
  tasks:
  - name: Replace the content of file
    shell:
      chdir: /etc
      cmd: echo	"Welcome to Apache server" > motd
- hosts: database
  tasks:
  - name: Replace the content of file
    shell:
      chdir: /etc
      cmd: echo	"Welcome to MySQL server" > motd
