---
- name: Use Conditionals to Control Play Execution
  hosts: webservers
  become: yes

  tasks:

    - name: debug msg 
      debug: msg="Total RAM is {{ ansible_memory_mb.real.total }}"
  
    - name: do if RAM > 2048 mb
      sysctl:
        name: vm.swappiness
        value: '10'
        state: present
      when: "ansible_memtotal_mb >= 2048"

    - name: do if RAM < 2048
      ansible.builtin.debug:
        msg: "Server memory less than 2048Mb"
      when: "ansible_memtotal_mb < 2048"
