#Create a playbook /home/automation/plays/motd.yml that runs on all inventory hosts and does the following:
#The playbook should replace any existing content of /etc/motd with text. Text depends on the host group.
#On hosts in the proxy host group the line should be “Welcome to HAProxy server”.
#On hosts in the webservers host group the line should be “Welcome to Apache server”.
#On hosts in the database host group the line should be “Welcome to MySQL server”.

---
- hosts: proxy
  tasks:
  - name: Replace the content of file
    shell:
      chdir: /etc
      cmd: echo "Welcome to HAProxy server" > motd
- hosts: webservers
  tasks:
  - name: Replace the content of file
    shell:
      chdir: /etc
      cmd: echo "Welcome to Apache server" > motd
- hosts: database
  tasks:
  - name: Replace the content of file
    shell:
      chdir: /etc
      cmd: echo "Welcome to MySQL server" > motd
