---
- hosts: all
  tasks:
  - name: replace the string
    replace: 
      path: /etc/ssh/sshd_config
      backup: yes
      regexp: "{{item.reg}}"
      replace: "{{item.replace}}"
    with_items:
    - { reg: '^(.*)Banner(.*)$', replace: 'Banner=/etc/motd' }
    - { reg: '^X11Forwarding(.*)$', replace: 'X11Forwarding no' }
    - { reg: '^(.*)MaxAuthTries(.*)$', replace: 'MaxAuthTries 3' }
