---
# defaults file for sample-mysql

block_device: /dev/sdb
volume_group: vg_database
pvs: /dev/sdb1
file_system_type: xfs
logical_volume: lv_mysql
volume_path: /dev/vg_database/lv_mysql
mount_volume_path: /mnt/mysql_backups
volume_src: /dev/vg_database/lv_mysql
destin_file: /etc/my.cnf
user: root
service: mysql
source_file: my.cnf.j2
port_number: 3306/tcp
package_2: MySQL-python
package_1: mysql-community-server
volume_size: 512m
partition_size: 800MiB
partition_number: 1
